<img src='https://srv.net.fje.edu/net2/images/logo_fje.svg' width='30%'><img src='https://avatars1.githubusercontent.com/u/305880?s=460&v=4' width='10%'>
####sergi.grau@fje.edu

# ![alt text](https://numpy.org/_static/numpy_logo.png)

## Introducció
L’objecte principal de NumPy és la matriu multidimensional homogènia. Es tracta d’una taula d’elements (normalment nombres), tots del mateix tipus, indexats per una tupla d’enters no negatius. Les dimensions NumPy s’anomenen eixos .

Per exemple, les coordenades d’un punt de l’espai 3D [1, 2, 1] tenen un eix. Aquest eix té tres elements, de manera que diem que té una longitud de 3. A l'exemple que es mostra a continuació, la matriu té dos eixos. El primer eix té una longitud de 2, el segon eix té una longitud de 3.

La classe de matriu de NumPy es diu ndarray o també es coneix com array. Tingueu en compte que numpy.array no és el mateix que la classe Python Library array.array , que només gestiona les matrius unidimensionals i ofereix menys funcionalitats. 

https://numpy.org/



In [0]:
#exemple de diferència de rendiment
from numpy import arange
from timeit import Timer

Nelements = 10000
Ntimeits = 10000

x = arange(Nelements)
y = range(Nelements)

t_numpy = Timer("x.sum()", "from __main__ import x")
t_list = Timer("sum(y)", "from __main__ import y")
print("numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits,))
print("list:  %.3e" % (t_list.timeit(Ntimeits)/Ntimeits,))

numpy: 1.168e-05
list:  1.842e-04


## Utilització
El primer que cal fer és importar la biblioteca i cridarem a una sèrie d'atributs de l'objecte ndarray

In [0]:
 [[ 1. , 0. , 0. ],
 [ 0. , 1. , 2. ]]


[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

In [0]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

print(a.shape) #nombre d'eixos
print(a.ndim) #dimensions
print(a.dtype.name) #tipus de dades contingudes de la matriu
print(a.itemsize) #mida en bytes de cada element
print(a.size) #nombre d'elements
print(type(a)) #tipus de dada

b = np.array([6, 7, 8])
print(b)
print(type(b))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


## Creació de matrius 

Hi ha diverses maneres de crear matrius.

Per exemple, podeu crear una matriu a partir d'una llista regular de Python o una tupla mitjançant la funció array . El tipus de la matriu resultant es dedueix del tipus d’elements de les seqüències.

In [0]:
import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

[2 3 4]
int64
float64


array transforma seqüències de seqüències en matrius bidimensionals, seqüències de seqüències de seqüències en matrius tridimensionals, etc.

In [0]:
b = np . array ([( 1.5 , 2 , 3 ), ( 4 , 5 , 6 )])
print(b)
c = np . array ( [ [ 1 , 2 ], [ 3 , 4 ] ], dtype = complex ) # especifiquem el tipus de dada en la creació
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


La funció zeros crea una matriu plena de zeros, les funcions ones crea una matriu plena de altres, i la funció empty crea una matriu el contingut inicial és aleatori i depèn de l'estat de la memòria. De manera predeterminada, el tipus de matriu creat és float64 .

In [0]:
print(np.zeros( ( 3 , 4 ) ))
print(np.ones( ( 2 , 3 , 4 ), dtype = np.int16 ))
print(np.empty ( ( 2 , 3 ) )) #inicialitzada al valor més petit                             

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


Per crear seqüències de nombres, NumPy proporciona una funció anàloga a la range que retorna les matrius en lloc de les llistes.

In [0]:
print(np.arange ( 10 , 30 , 5 ))
print(np.arange ( 0 , 2 , 0.3 ))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


Quan s'utilitza un arange amb arguments de coma flotant, generalment no és possible predir el nombre d'elements obtinguts, a causa de la precisió finita del punt flotant. Per aquesta raó, sol ser millor utilitzar la funció linspace que rep com a argument el nombre d’elements que volem, en lloc del pas

In [0]:
from numpy import pi
print(np.linspace( 0 , 2 , 9 ))                 # 9 nombres des de 0 a 2

x = np.linspace( 0 , 2 * pi , 10 )        
f = np.sin( x )
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


Si una matriu és massa gran per imprimir-la, NumPy ometirà automàticament la part central de la matriu i només imprimeix les cantonades:

In [0]:
#np.set_printoptions ( threshold = sys . maxsize ) permet indicar els elements de la impressió
#import sys
#np.set_printoptions( threshold = sys.maxsize)
print ( np.arange ( 10000 ))
print ( np.arange ( 10000 ).reshape ( 100 , 100 )) # reshape canvia la dimensió d'una matriu

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Operacions bàsiques
Els operadors aritmètics en matrius s'apliquen de forma elemental. Es crea una nova matriu i s'omple amb el resultat.



In [0]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)

c = a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


A diferència de molts llenguatges de matrius, l'operador de producte * opera elementalment en matrius NumPy. El producte matricial es pot realitzar mitjançant l'operador @ (en python> = 3.5) o la funció o mètode de punts:

In [0]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
print(A * B) #producte element a element
print(A @ B ) #producte matricial o A.dot(B)


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


Algunes operacions, com ara + = i * =, actuen al seu lloc per modificar una matriu existent en lloc de crear-ne una de nova.

In [0]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)


b += a
print(b)

#a += b    # b no es converteix automàticament al tipus d'a  
a=a+b
print(a)

[[3 3 3]
 [3 3 3]]
[[3.59663419 3.49998099 3.09573874]
 [3.54430324 3.11299124 3.5273433 ]]
[[6.59663419 6.49998099 6.09573874]
 [6.54430324 6.11299124 6.5273433 ]]


Moltes operacions unàries, com ara calcular la suma de tots els elements de la matriu, s’implementen com a mètodes de la classe ndarray.

In [0]:
a = np.random.randint(5, size=(2,3)) #valors aleatoris entre 0 i 4, en una matriu 2x3
print(a)

print(a.sum())
print(a.min())
print(a.max())

[[4 2 1]
 [0 3 2]]
12
0
4


De manera predeterminada, aquestes operacions s'apliquen a la matriu com si es tractés d'una llista de números, independentment de la seva forma. Tanmateix, especificant el paràmetre de l’eix podeu aplicar una operació al llarg de l’eix especificat d’una matriu

In [0]:
b = np.arange(12).reshape(3,4)
print(b)

print(b.sum(axis=0))                            # suma de cada columna
print(b.min(axis=1))                            # min de cada fila
print(b.cumsum(axis=1))                        # suma acumulada de cada fila

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


##Funcions
NumPy proporciona funcions matemàtiques familiars, com ara pecat, cos i exp. A NumPy, aquestes s'anomenen "funcions universals" (ufunc). Dins de NumPy, aquestes funcions funcionen de manera elemental en una matriu, produint una matriu com a sortida. Les funcions són all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [0]:
B = np.arange(3)
print(B)

print(np.exp(B)) #nombre e
print(np.sqrt(B))

C = np.array([2., -1., 4.])
print(C)
print(np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[ 2. -1.  4.]
[2. 0. 6.]


## Indexar, retallar i iterar
Les matrius unidimensionals es poden indexar, tallar i iterar, igual que les llistes i altres seqüències de Python.

In [0]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
c= a.copy() #copia una matriu
b= a[:6:2] 
print(b)
print(c[ : :-1])  # inverteix a

for i in a:
    print(i**2)


[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[ 0  8 64]
[729 512 343 216 125  64  27   8   1   0]
0
1
64
729
4096
15625
46656
117649
262144
531441


Les matrius multidimensionals poden tenir un índex per eix. Aquests índexs es donen en una tupla separada per comes:

In [0]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)

print(b[2,3])
print(b[0:5, 1])                     # cada fila a la 2a columna de b
print(b[ : ,1])                     # idem anterior
print(b[1:3, : ])                  # cada columna a la 2a i 3a fila de b

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


##Algebra simple

In [0]:
import numpy as np
a = np.array([[1.0, -3.0], [1.0, 5.0]])
print(a)

print(a.transpose()) # matriu trasposada
print(np.linalg.inv(a)) # matriu inversa

#solució de sistemes linials
# x-3y = 2
# x+5y = 10
y = np.array([[2.], [10.]])
print(np.linalg.solve(a, y))


[[ 1. -3.]
 [ 1.  5.]]
[[ 1.  1.]
 [-3.  5.]]
[[ 0.625  0.375]
 [-0.125  0.125]]
[[5.]
 [1.]]
